### ISSUE TITLE
To-do 24 May

### ISSUE THREAD

**Issue by bucketfish0000** [bucketfish0000/reservoir_restructure#2]
- [ ] Fix KR, GR
- [ ] Fix MC computing
- [x] Lyapunov
- [ ] Learning Curve
- [x] Fix Mackey-Glass benchmark 
- [ ] Add unit tests for qualification (0/5)
- [ ] Add unit tests for network (0/??)
- [ ] Re-organize notebook
